

CONFIRM_EXCHANGE = 18
SEND_AMOUNT_PRIZE = 17
CONFIRM_PRIZE = 16
SELECT_PRIZE = 15
n = 14
SELECT_LANG, SEND_NAME, SEND_CONTACT, CLICK_LANG, ALL_SETTINGS, LANG_SETTINGS, NAME_SETTINGS, PHONE_SETTINGS, SELECT_PRODUCT, CONFIRM_PRODUCT, SEND_AMOUNT, SEND_PHOTO, SEND_CITY, SEND_PHOTO2 = range(0, n)