
CONFIRM_EXCHANGE_NEW = 26
SEND_AMOUNT_PRIZE_NEW = 25
CONFIRM_PRIZE_NEW = 24
SELECT_PRIZE_NEW = 23
SEND_PHOTO2_NEW = 22
SEND_PHOTO_NEW = 21
SEND_STORE_TITLE_NEW = 20

SEND_STORE_TITLE = 19
CONFIRM_EXCHANGE = 18
SEND_AMOUNT_PRIZE = 17
CONFIRM_PRIZE = 16
SELECT_PRIZE = 15
n = 14
SELECT_LANG, SEND_NAME, SEND_CONTACT, CLICK_LANG, ALL_SETTINGS, LANG_SETTINGS, NAME_SETTINGS, PHONE_SETTINGS, SELECT_PRODUCT, CONFIRM_PRODUCT, SEND_AMOUNT, SEND_PHOTO, SEND_CITY, SEND_PHOTO2 = range(0, n)